seed: 1234
logging_level: INFO

debug: False

tensor_parallel_size: 1

environ:
  model_cache: HF_MODEL_CACHE
  dataset_cache: HF_DATASETS_CACHE
  openai_api_key: OPENAI_API_KEY
  dummy_api_key: DUMMY_API_KEY

model:
  name: meta-llama/Llama-3.2-1B-Instruct

path: 
  output: /skt_ai/output

dataset:
  train: /skt_ai/data_0915_1/data_half.jsonl

generation:
  template_id: 0
  num_generations: 1
  num_demonstrations: 2
  max_new_tokens: 3000
  temperature: 0.0
  top_p: 1.0
  top_logprobs: 100

training:
  num_training_epochs: 0
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 1e-3